[package]
name = "rytmos-engrave"
version = "0.1.0"
edition = "2021"
description = "Music notation renderer for embedded devices"

[dependencies]
rytmos-symbols = { path = "../rytmos-symbols" }
embedded-graphics = "0.8.1"
heapless = "0.8.0"
log = "0.4.22"
libm = "0.2.8"
